# Contributors:
# - Josh Marsden

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/swe642
    username: swe642
    password: hw3
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
